#!/usr/bin/env lua
-- Lubyk alters the search path to only work with it's own
-- global directory, the user's personal lib and the current
-- path's lib.
-- local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua
--package.path = "./?.lua;./lib/?.lua"
require 'lubyk'

local action = arg[1]
table.remove(arg, 1)
if action == '--test' or action == '-t' then
  require 'test'
  local all = test.all
  test.all = function() end -- dummy

  test.load_all(unpack(arg))
  all()
end
