#!/bin/sh

# MacOS
f=`dirname "$0"`
# Resources
r="$f/../Resources"
lubyk="$r/lubyk"

INSTALL=''
# Check if lubyk is installed
INSTALLED=`/usr/local/bin/lubyk -v 2>&1`
CURRENT=`$lubyk -v 2>&1`
if [ "$INSTALLED" != "$CURRENT" ] 
then
  # We need to install
  INSTALL="--install"
else
  if [ ! -f /usr/local/share/lua/5.1/lubyk.lua ]
  then
    INSTALL="--install"
  fi
fi

app="$r/app.lua"

exec "$lubyk" "$app" "$f/../../../lib" "$INSTALL" "$1"
