/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Registration
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "mdns/Registration.h"

using namespace mdns;

/** Cast (class_name)
 * 
 */
static int Registration__cast_(lua_State *L) {

  Registration *self = *((Registration **)dub_checksdata_n(L, 1, "mdns.Registration"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "mdns.AbstractRegistration")) break;
      *retval__ = static_cast<AbstractRegistration *>(self);
      return 1;
    }
  }
  return 0;
}

/** mdns::Registration::Registration(const char *service_type, const char *name, uint port, const char *txt)
 * include/mdns/Registration.h:49
 */
static int Registration_Registration(lua_State *L) {
  try {
    const char *service_type = dub_checkstring(L, 1);
    const char *name = dub_checkstring(L, 2);
    uint port = dub_checkint(L, 3);
    const char *txt = dub_checkstring(L, 4);
    Registration *retval__ = new Registration(service_type, name, port, txt);
    retval__->pushobject(L, retval__, "mdns.Registration", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "mdns.Registration.Registration: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mdns.Registration.Registration: Unknown exception");
  }
  return dub_error(L);
}

/** mdns::Registration::~Registration()
 * include/mdns/Registration.h:52
 */
static int Registration__Registration(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "mdns.Registration"));
    if (userdata->gc) {
      Registration *self = (Registration *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "mdns.Registration.~Registration: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mdns.Registration.~Registration: Unknown exception");
  }
  return dub_error(L);
}

/** int mdns::Registration::fd()
 * include/mdns/Registration.h:55
 */
static int Registration_fd(lua_State *L) {
  try {
    Registration *self = *((Registration **)dub_checksdata(L, 1, "mdns.Registration"));
    lua_pushnumber(L, self->fd());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "mdns.Registration.fd: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mdns.Registration.fd: Unknown exception");
  }
  return dub_error(L);
}

/** LuaStackSize mdns::Registration::getService(lua_State *L)
 * include/mdns/Registration.h:61
 */
static int Registration_getService(lua_State *L) {
  try {
    Registration *self = *((Registration **)dub_checksdata(L, 1, "mdns.Registration"));
    return self->getService(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "mdns.Registration.getService: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mdns.Registration.getService: Unknown exception");
  }
  return dub_error(L);
}

/** const char* mdns::AbstractRegistration::name()
 * include/mdns/AbstractRegistration.h:48
 */
static int Registration_name(lua_State *L) {
  try {
    Registration *self = *((Registration **)dub_checksdata(L, 1, "mdns.Registration"));
    lua_pushstring(L, self->name());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "mdns.AbstractRegistration.name: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mdns.AbstractRegistration.name: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int Registration___tostring(lua_State *L) {
  Registration *self = *((Registration **)dub_checksdata_n(L, 1, "mdns.Registration"));
  lua_pushfstring(L, "mdns.Registration: %p (%s)", self, self-> name());
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Registration_member_methods[] = {
  { "_cast_"       , Registration__cast_  },
  { "new"          , Registration_Registration },
  { "__gc"         , Registration__Registration },
  { "fd"           , Registration_fd      },
  { "getService"   , Registration_getService },
  { "name"         , Registration_name    },
  { "__tostring"   , Registration___tostring },
  { NULL, NULL},
};


extern "C" int luaopen_mdns_Registration(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "mdns.Registration");
  // <mt>

  // register member methods
  luaL_register(L, NULL, Registration_member_methods);
  // save meta-table in mdns
  dub_register(L, "mdns", "Registration");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
