/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library mdns_core
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "mdns/Context.h"
#include "mdns/Registration.h"
#include "mdns/Browser.h"
#include "mdns/Service.h"

using namespace mdns;

extern "C" {
int luaopen_mdns_Context(lua_State *L);
int luaopen_mdns_Registration(lua_State *L);
int luaopen_mdns_Browser(lua_State *L);
int luaopen_mdns_Service(lua_State *L);
}

// --=============================================== FUNCTIONS

static const struct luaL_Reg mdns_core_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_mdns_core(lua_State *L) {
  luaopen_mdns_Context(L);
  luaopen_mdns_Registration(L);
  luaopen_mdns_Browser(L);
  luaopen_mdns_Service(L);

  luaL_register(L, NULL, mdns_core_functions);
  // <lib>
  lua_pop(L, 1);
  return 0;
}
