/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library zmq_core
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "zmq/Socket.h"
#include "zmq/Poller.h"

using namespace zmq;
using namespace lubyk;

extern "C" {
int luaopen_zmq_Socket(lua_State *L);
int luaopen_zmq_Poller(lua_State *L);
}

// --=============================================== FUNCTIONS

static const struct luaL_Reg zmq_core_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_zmq_core(lua_State *L) {
  luaopen_zmq_Socket(L);
  luaopen_zmq_Poller(L);

  luaL_register(L, NULL, zmq_core_functions);
  // <lib>
  lua_pop(L, 1);
  return 0;
}
