/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library mdns_core
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "mdns/Context.h"
#include "mdns/Registration.h"
#include "mdns/Browser.h"
#include "mdns/Service.h"

using namespace mdns;

extern "C" {
int luaopen_mdns_Context(lua_State *L);
int luaopen_mdns_Registration(lua_State *L);
int luaopen_mdns_Browser(lua_State *L);
int luaopen_mdns_Service(lua_State *L);
}

// --=============================================== FUNCTIONS
static const struct luaL_Reg mdns_core_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_mdns_core(lua_State *L) {
  luaopen_mdns_Context(L);
  luaopen_mdns_Registration(L);
  luaopen_mdns_Browser(L);
  luaopen_mdns_Service(L);

  // Create the table which will contain all the constants
  lua_getfield(L, LUA_GLOBALSINDEX, "mdns_core");
  if (lua_isnil(L, -1)) {
    // no global table called mdns_core
    lua_pop(L, 1);
    lua_newtable(L);
    // <lib>
    lua_pushvalue(L, -1);
    // <lib> <lib>
    // _G.mdns_core = <lib>
    lua_setglobal(L, "mdns_core");
    // <lib>
  }
  // <lib>
  luaL_register(L, NULL, mdns_core_functions);
  // <lib>
  lua_pop(L, 1);
  return 0;
}
