/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library lk
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"


extern "C" {
}

// --=============================================== FUNCTIONS
static const struct luaL_Reg lk_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_lk_more_c(lua_State *L) {

  // Create the table which will contain all the constants
  lua_getfield(L, LUA_GLOBALSINDEX, "lk");
  if (lua_isnil(L, -1)) {
    // no global table called lk
    lua_pop(L, 1);
    lua_newtable(L);
    // <lib>
    lua_pushvalue(L, -1);
    // <lib> <lib>
    // _G.lk = <lib>
    lua_setglobal(L, "lk");
    // <lib>
  }
  // <lib>
  luaL_register(L, NULL, lk_functions);
  // <lib>
  lua_pop(L, 1);
  return 0;
}
