/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library lk_core
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "lk/Finalizer.h"
#include "lk/Socket.h"
#include "lk/SelectCallback.h"
#include "lk/Debug.h"

using namespace lk;

extern "C" {
int luaopen_lk_Finalizer(lua_State *L);
int luaopen_lk_Socket(lua_State *L);
int luaopen_lk_SelectCallback(lua_State *L);
int luaopen_lk_Debug(lua_State *L);
}

// --=============================================== FUNCTIONS

static const struct luaL_Reg lk_core_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_lk_core(lua_State *L) {
  luaopen_lk_Finalizer(L);
  luaopen_lk_Socket(L);
  luaopen_lk_SelectCallback(L);
  luaopen_lk_Debug(L);

  luaL_register(L, NULL, lk_core_functions);
  // <lib>
  lua_pop(L, 1);
  return 0;
}
