/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Socket
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "lk/Socket.h"

using namespace lk;

/** lk::Socket::Socket(int socket_type)
 * include/lk/Socket.h:106
 */
static int Socket_Socket(lua_State *L) {
  try {
    int socket_type = dub_checkint(L, 1);
    Socket *retval__ = new Socket(socket_type);
    retval__->pushobject(L, retval__, "lk.Socket", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "Socket: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Socket: Unknown exception");
  }
  return dub_error(L);
}

/** lk::Socket::~Socket()
 * include/lk/Socket.h:109
 */
static int Socket__Socket(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "lk.Socket"));
    if (userdata->gc) {
      Socket *self = (Socket *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~Socket: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~Socket: Unknown exception");
  }
  return dub_error(L);
}

/** void lk::Socket::close()
 * include/lk/Socket.h:113
 */
static int Socket_close(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    self->close();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "close: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "close: Unknown exception");
  }
  return dub_error(L);
}

/** int lk::Socket::bind(const char *localhost=NULL, int port=0)
 * include/lk/Socket.h:123
 */
static int Socket_bind(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      const char *localhost = dub_checkstring(L, 2);
      int port = dub_checkint(L, 3);
      lua_pushnumber(L, self->bind(localhost, port));
      return 1;
    } else if (top__ >= 2) {
      const char *localhost = dub_checkstring(L, 2);
      lua_pushnumber(L, self->bind(localhost));
      return 1;
    } else {
      lua_pushnumber(L, self->bind());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "bind: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "bind: Unknown exception");
  }
  return dub_error(L);
}

/** bool lk::Socket::connect(const char *host, int port)
 * include/lk/Socket.h:128
 */
static int Socket_connect(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    const char *host = dub_checkstring(L, 2);
    int port = dub_checkint(L, 3);
    lua_pushboolean(L, self->connect(host, port));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "connect: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "connect: Unknown exception");
  }
  return dub_error(L);
}

/** void lk::Socket::connectFinish()
 * include/lk/Socket.h:132
 */
static int Socket_connectFinish(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    self->connectFinish();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "connectFinish: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "connectFinish: Unknown exception");
  }
  return dub_error(L);
}

/** void lk::Socket::listen(int backlog=BACKLOG)
 * include/lk/Socket.h:137
 */
static int Socket_listen(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int backlog = dub_checkint(L, 2);
      self->listen(backlog);
      return 0;
    } else {
      self->listen();
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "listen: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "listen: Unknown exception");
  }
  return dub_error(L);
}

/** LuaStackSize lk::Socket::accept(lua_State *L)
 * include/lk/Socket.h:142
 */
static int Socket_accept(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    return self->accept(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "accept: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "accept: Unknown exception");
  }
  return dub_error(L);
}

/** void lk::Socket::setRecvTimeout(int timeout)
 * include/lk/Socket.h:144
 */
static int Socket_setRecvTimeout(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    int timeout = dub_checkint(L, 2);
    self->setRecvTimeout(timeout);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setRecvTimeout: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setRecvTimeout: Unknown exception");
  }
  return dub_error(L);
}

/** void lk::Socket::setSendTimeout(int timeout)
 * include/lk/Socket.h:148
 */
static int Socket_setSendTimeout(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    int timeout = dub_checkint(L, 2);
    self->setSendTimeout(timeout);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setSendTimeout: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setSendTimeout: Unknown exception");
  }
  return dub_error(L);
}

/** void lk::Socket::setNonBlocking()
 * include/lk/Socket.h:152
 */
static int Socket_setNonBlocking(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    self->setNonBlocking();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setNonBlocking: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setNonBlocking: Unknown exception");
  }
  return dub_error(L);
}

/** LuaStackSize lk::Socket::recv(lua_State *L)
 * include/lk/Socket.h:174
 */
static int Socket_recv(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    return self->recv(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "recv: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "recv: Unknown exception");
  }
  return dub_error(L);
}

/** int lk::Socket::send(lua_State *L)
 * include/lk/Socket.h:180
 */
static int Socket_send(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushnumber(L, self->send(L));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "send: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "send: Unknown exception");
  }
  return dub_error(L);
}

/** const char* lk::Socket::localHost() const
 * include/lk/Socket.h:197
 */
static int Socket_localHost(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushstring(L, self->localHost());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localHost: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localHost: Unknown exception");
  }
  return dub_error(L);
}

/** int lk::Socket::localPort() const
 * include/lk/Socket.h:201
 */
static int Socket_localPort(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushnumber(L, self->localPort());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localPort: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localPort: Unknown exception");
  }
  return dub_error(L);
}

/** const char* lk::Socket::remoteHost() const
 * include/lk/Socket.h:205
 */
static int Socket_remoteHost(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushstring(L, self->remoteHost());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "remoteHost: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "remoteHost: Unknown exception");
  }
  return dub_error(L);
}

/** int lk::Socket::remotePort() const
 * include/lk/Socket.h:209
 */
static int Socket_remotePort(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushnumber(L, self->remotePort());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "remotePort: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "remotePort: Unknown exception");
  }
  return dub_error(L);
}

/** int lk::Socket::port() const
 * include/lk/Socket.h:213
 */
static int Socket_port(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushnumber(L, self->port());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "port: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "port: Unknown exception");
  }
  return dub_error(L);
}

/** int lk::Socket::fd() const
 * include/lk/Socket.h:217
 */
static int Socket_fd(lua_State *L) {
  try {
    Socket *self = *((Socket **)dub_checksdata(L, 1, "lk.Socket"));
    lua_pushnumber(L, self->fd());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "fd: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "fd: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int Socket___tostring(lua_State *L) {
  Socket *self = *((Socket **)dub_checksdata_n(L, 1, "lk.Socket"));
  lua_pushfstring(L, "lk.Socket: %p (%s:%d --> %s:%d)", self, self-> localHost() , self-> localPort() , self-> remoteHost() , self-> remotePort() );
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Socket_member_methods[] = {
  { "new"          , Socket_Socket        },
  { "__gc"         , Socket__Socket       },
  { "close"        , Socket_close         },
  { "bind"         , Socket_bind          },
  { "connect"      , Socket_connect       },
  { "connectFinish", Socket_connectFinish },
  { "listen"       , Socket_listen        },
  { "accept"       , Socket_accept        },
  { "setRecvTimeout", Socket_setRecvTimeout },
  { "setSendTimeout", Socket_setSendTimeout },
  { "setNonBlocking", Socket_setNonBlocking },
  { "recv"         , Socket_recv          },
  { "send"         , Socket_send          },
  { "localHost"    , Socket_localHost     },
  { "localPort"    , Socket_localPort     },
  { "remoteHost"   , Socket_remoteHost    },
  { "remotePort"   , Socket_remotePort    },
  { "port"         , Socket_port          },
  { "fd"           , Socket_fd            },
  { "__tostring"   , Socket___tostring    },
  { NULL, NULL},
};

// --=============================================== CONSTANTS
static const struct dub_const_Reg Socket_const[] = {
  { "TCP"          , Socket::TCP          },
  { "UDP"          , Socket::UDP          },
  { NULL, 0},
};

extern "C" int luaopen_lk_Socket(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "lk.Socket");
  // <mt>
  // register class constants
  dub_register_const(L, Socket_const);

  // register member methods
  luaL_register(L, NULL, Socket_member_methods);
  // save meta-table in lk
  dub_register(L, "lk", "Socket_core");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
